# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "uhci_hcd" "hpsa" "usbhid" "usb_storage" "sd_mod" "sr_mod" "e1000e" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "srpool/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "srpool/home";
      fsType = "zfs";
    };

  fileSystems."/home/alex" =
    { device = "srpool/home/alex";
      fsType = "zfs";
    };

  fileSystems."/gitlab" =
    { device = "srpool/gitlab";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    #{ device = "/dev/disk/by-uuid/81997baa-729c-42ac-bbef-568ccee2562b";
    { device = "/dev/md127";
      fsType = "ext4";
    };

  swapDevices = [ {device = "/dev/zvol/srpool/swap"; } ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
